apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: keycloak
    repoURL: https://github.com/NeorCloud/arvan-exchange-sh1-compute1.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - Prune=true
    - SelfHeal=true
